version: '1.0.0'
services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    restart: always
    #외부와 소통하는 경우에는 ports로 포트 설정.
    ports:
      - "443:443"
      - "80:80"
    volumes:
    #docker-compose.yml과 같은 레벨에 둔 nginx.conf를 mount.
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/geoip.dat:/etc/nginx.d/geoip.dat

      - ./nginx/ssl/import.crt:/etc/nginx/ssl/import.crt
      - ./nginx/ssl/import.key:/etc/nginx/ssl/import.key
      
    networks:
      - import_cicd_network
    environment:
      - TZ=Asia/Seoul
networks:
  import_cicd_network:
    driver: bridge
    external: true